language: scala
sudo: false
cache:
  directories:
    - $HOME/.ivy2
matrix:
  include:
    - jdk: openjdk6
      scala: 2.10.4
      env: TEST_SPARK_VERSION="1.2.1"
    - jdk: openjdk7
      scala: 2.10.4
      env: TEST_SPARK_VERSION="1.2.1"
    - jdk: oraclejdk7
      scala: 2.10.4
      env: TEST_SPARK_VERSION="1.2.1"
    - jdk: openjdk6
      scala: 2.10.4
      env: TEST_SPARK_VERSION="1.3.1"
    - jdk: openjdk7
      scala: 2.10.4
      env: TEST_SPARK_VERSION="1.3.1"
    - jdk: oraclejdk7
      scala: 2.10.4
      env: TEST_SPARK_VERSION="1.3.1"
    - jdk: openjdk6
      scala: 2.10.4
      env: TEST_SPARK_VERSION="1.4.1"
    - jdk: openjdk7
      scala: 2.10.4
      env: TEST_SPARK_VERSION="1.4.1"
    - jdk: oraclejdk7
      scala: 2.10.4
      env: TEST_SPARK_VERSION="1.4.1"
    - jdk: oraclejdk8
      scala: 2.10.4
      env: TEST_SPARK_VERSION="1.4.1"
script:
  - sbt -Dspark.testVersion=$TEST_SPARK_VERSION ++$TRAVIS_SCALA_VERSION coverage test
  - sbt ++$TRAVIS_SCALA_VERSION scalastyle
after_success:
  - bash <(curl -s https://codecov.io/bash)
